<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="4" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="67" started-at="2020-06-03T07:41:58 IST" finished-at="2020-06-03T07:41:58 IST">
    <groups>
      <group name="pre">
        <method signature="Booking.search()[pri:0, instance:tests.Booking@5ec0a365]" name="search" class="tests.Booking"/>
        <method signature="Booking.select()[pri:0, instance:tests.Booking@5ec0a365]" name="select" class="tests.Booking"/>
      </group> <!-- pre -->
      <group name="post">
        <method signature="Booking.checkout()[pri:0, instance:tests.Booking@5ec0a365]" name="checkout" class="tests.Booking"/>
        <method signature="Booking.confirm()[pri:0, instance:tests.Booking@5ec0a365]" name="confirm" class="tests.Booking"/>
      </group> <!-- post -->
      <group name="sanity">
        <method signature="Booking.checkout()[pri:0, instance:tests.Booking@5ec0a365]" name="checkout" class="tests.Booking"/>
        <method signature="Booking.confirm()[pri:0, instance:tests.Booking@5ec0a365]" name="confirm" class="tests.Booking"/>
        <method signature="Booking.search()[pri:0, instance:tests.Booking@5ec0a365]" name="search" class="tests.Booking"/>
        <method signature="Booking.select()[pri:0, instance:tests.Booking@5ec0a365]" name="select" class="tests.Booking"/>
      </group> <!-- sanity -->
    </groups>
    <test name="Booking" duration-ms="67" started-at="2020-06-03T07:41:58 IST" finished-at="2020-06-03T07:41:58 IST">
      <class name="tests.Booking">
        <test-method status="FAIL" signature="checkout()[pri:0, instance:tests.Booking@5ec0a365]" name="checkout" duration-ms="11" started-at="2020-06-03T07:41:58 IST" finished-at="2020-06-03T07:41:58 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.fail(Assert.java:102)
at tests.Booking.checkout(Booking.java:22)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkout -->
        <test-method status="PASS" signature="confirm()[pri:0, instance:tests.Booking@5ec0a365]" name="confirm" duration-ms="1" started-at="2020-06-03T07:41:58 IST" finished-at="2020-06-03T07:41:58 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- confirm -->
        <test-method status="FAIL" signature="search()[pri:0, instance:tests.Booking@5ec0a365]" name="search" duration-ms="1" started-at="2020-06-03T07:41:58 IST" finished-at="2020-06-03T07:41:58 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.fail(Assert.java:102)
at tests.Booking.search(Booking.java:10)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- search -->
        <test-method status="PASS" signature="select()[pri:0, instance:tests.Booking@5ec0a365]" name="select" duration-ms="1" started-at="2020-06-03T07:41:58 IST" finished-at="2020-06-03T07:41:58 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- select -->
      </class> <!-- tests.Booking -->
    </test> <!-- Booking -->
  </suite> <!-- Suite -->
</testng-results>
